server:
  port: 8102
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://replica1:8002/eureka/,http://replica2:8003/eureka/ #同时注册到两个注册中心
      defaultZone: http://admin:123456@localhost:8002/eureka/ # 注册到security 注册中心上 格式   http://${username}:${password}@${hostname}:${port}/eureka/
